# Generated by Django 2.1.5 on 2019-01-24 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('code', models.CharField(max_length=13, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketPurchase',
            fields=[
                ('ticket',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.PROTECT,
                     primary_key=True,
                     serialize=False,
                     to='api.Ticket')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SouvenirRedeem',
            fields=[
                ('ticket_purchase',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.PROTECT,
                     primary_key=True,
                     serialize=False,
                     to='api.TicketPurchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
