# Generated by Django 2.1.5 on 2019-01-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souvenirredeem',
            name='ticket_purchase',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                related_name='souvenir_redeem',
                serialize=False,
                to='api.TicketPurchase'),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='ticket',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                related_name='ticket_purchase',
                serialize=False,
                to='api.Ticket'),
        ),
    ]
